//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KsbVisits
    {
        public int ID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> VisitTypeID { get; set; }
        public string Remarks { get; set; }
        public byte[] Picture1 { get; set; }
        public string Picture2 { get; set; }
    
        public virtual Retailer Retailer { get; set; }
        public virtual VisitPurpose VisitPurpose { get; set; }
    }
}
